### ISSUE TITLE
Possible to make alloc optional?

### ISSUE THREAD

**Issue by sphw** [rkyv/bytecheck#23]
`bytecheck` supports no_std, but as of https://github.com/rkyv/bytecheck/commit/d38d2cea168c210adb1b54736df605965b54772d it requires `alloc` to be available. Since the use of alloc is minimal and restricted to error handling, would it be possible to feature gate code requiring alloc?

**Comment by djkoloski** [comment]
I think it would be possible but it would be a breaking change. I prototyped a change a while ago that eagerly sunk generated errors to some output and that could do the trick. I'm open to more ideas on how to approach this problem!

**Comment by sphw** [comment]
Would adding a `no-alloc feature flag work? Without it the current behavior could be kept, but when enabled it could disable boxed errors. Definitely not the cleanest approach, but it could be changed later in a major release.

**Comment by djkoloski** [comment]
Unfortunately putting existing behavior behind a default feature is a breaking change for anyone who has `default-features = false` in their `Cargo.toml`. This looks like a good candidate for the next major release though.

The other alternative is changing the behavior based on a non-default `no-alloc` flag. This isn't _great_ because features should be additive, but it would technically be possible.

**Comment by sphw** [comment]
> The other alternative is changing the behavior based on a non-default no-alloc flag. This isn't great because features should be additive, but it would technically be possible.

That's essentially what I was advocating for. Definitely inelegant and not best-practices, but would fix the problem in the short term for anyone who needs it. The next major release could change the behavior. If you are open to it I can make a PR with that change

**Comment by djkoloski** [comment]
In this particular situation, I'd prefer to leave things as they are for bytecheck 0.6.*. For this specific situation, I'd prefer to leave things as maximally stable as possible. However, I welcome PRs and would be very happy to introduce it in the next major version. If you'd like to create a fork for 0.6 with `no-alloc` support and use that until 0.7 is ready with this support, you can patch your cargo workspace by adding this to your root `Cargo.toml`:

```toml
[patch.crates-io]
bytecheck = { git = "https://github.com/sphw/bytecheck" }
```

And again, I welcome this kind of work! I would just prefer to put it in a major version update instead of patching it into a minor one.

**Comment by sphw** [comment]
Just wanted to drop my branch in here that includes a version of these changes https://github.com/sphw/bytecheck/tree/alloc-feature. It is not backwards compatible, and I'm not sure if it's exactly what you were after. Happy to open a PR if it is

**Comment by djkoloski** [comment]
Bytecheck 0.8 supports fully no-std, no-alloc use cases.
