### ISSUE TITLE
Safety and modularity

### ISSUE THREAD

**Issue by sffc** [rkyv/bytecheck#6]
The namesake trait, CheckBytes, has an unsafe function:

```rust
pub trait CheckBytes<C: ?Sized> {
    /// The error that may result from checking the type.
    type Error: Error + 'static;

    /// Checks whether the given pointer points to a valid value within the
    /// given context.
    ///
    /// # Safety
    ///
    /// The passed pointer must be aligned and point to enough bytes to
    /// represent the type.
    unsafe fn check_bytes<'a>(value: *const Self, context: &mut C) -> Result<&'a Self, Self::Error>;
}
```

I don't see why it can't be safe.  Why not do

```rust
pub trait SafeCheckBytes<const N: unsigned> {
    /// The error that may result from checking the type.
    type Error: Error + 'static;

    fn check_bytes(bytes: [u8; N]) -> Result<(), Self::Error>;

    fn get_alignment() -> usize;
}
```

Also, it would be nice to decouple *bit validation* from *alignment validation*.  By decoupling these operations, the trait becomes more versatile and allows for interesting eager vs lazy validation of untrusted data.  Above, I suggested a simple function that returns the required alignment of the data.

**Comment by djkoloski** [comment]
The primary reason for using aligned pointers rather than checking byte slices is for better performance. A good example of this for builtin types is the [nonzero integer checks](https://github.com/djkoloski/bytecheck/blob/master/bytecheck/src/lib.rs#L656), which load the underlying integer type and check that it's not 0. If the byte slices weren't aligned, an unaligned read would be required which could add up to a big performance hit for large arrays. Since the attitude should be performance-by-default, I think that requiring alignment is a good default to have.

Depending on how far you're willing to go, you can write `CheckBytes` implementations that don't require alignment:

```rust
#[repr(transparent)]
pub struct UnalignedNonZeroU32 {
    bytes: [u8; 4],
}

impl<C: ?Sized> CheckBytes<C> for UnalignedNonZeroU32
where
    NonZeroU32: CheckBytes<C>,
{
    type Error = <NonZeroU32 as CheckBytes<C>>::Error;
    
    unsafe fn check_bytes<'a>(value: *const Self, context: &mut C) -> Result<&'a Self, Self::Error> {
        let value = &*value;
        let aligned = u32::from_ne_bytes(value.bytes);
        let as_aligned = (&aligned as *const [u8; 4]).cast::<NonZeroU32>();
        NonZeroU32::check_bytes(as_aligned, context)?;
        Ok(value)
    }
}
```

What cases were you interested in where you would want to validate unaligned memory? I don't think that decoupling alignment from bit validation would enable lazy evaluation without building out some extra infrastructure that would work with the aligned `check_bytes` already.

**Comment by sffc** [comment]
Thanks for the reply!

For nonzero integers, it would be useful to see data that forcing alignment enhances performance.  Two counter-hypotheses: (1) we could simply check that the bytes themselves are zero without casting to the integer type, or (2) perhaps unaligned reads are not actually inefficient in certain situations (e.g., perhaps for types that fit in registers); I have some early data from experiments I've been doing to suggest this.

> What cases were you interested in where you would want to validate unaligned memory?

I've been working on a prototype in https://github.com/unicode-org/icu4x/pull/630 where I back an array of `u32`s with `&[u8]`, using lazy unaligned reads when accessing elements from it.  I would like to generalize to types that require byte validation.

**Comment by djkoloski** [comment]
Closing for now since the referenced PR was closed, feel free to reopen or file a new issue if this is something you want.
